### ISSUE TITLE
Segfault on collector startup with awsecscontainermetrics receiver

### ISSUE THREAD

**Issue by nathanpeck** [aws-observability/aws-otel-collector#174] opened 2020-11-25 17:53 UTC
I am getting the following segfault on starting the `amazon/aws-otel-collector:latest` container with `AWS OTel Collector version: v0.4.0`

```
1606326170999,AWS OTel Collector version: v0.4.0
1606326170999,"2020-11-25T17:42:50.999Z    INFO    service/service.go:397  Starting AWS OTel Collector...  {""Version"": ""v0.4.0"", ""GitHash"": ""be64e63fbd972170e024cbf10d41b7fad0e94394"", ""NumCPU"": 2}"
1606326170999,2020-11-25T17:42:50.999Z  INFO    service/service.go:241  Setting up own telemetry...
1606326171000,"2020-11-25T17:42:51.000Z    INFO    service/telemetry.go:101    Serving Prometheus metrics  {""address"": ""localhost:8888"", ""level"": 0, ""service.instance.id"": ""88ab22d1-3030-4197-9ae7-c2264727402b""}"
1606326171001,2020-11-25T17:42:51.000Z  INFO    service/service.go:278  Loading configuration...
1606326171011,2020-11-25T17:42:51.011Z  INFO    service/service.go:289  Applying configuration...
1606326171011,2020-11-25T17:42:51.011Z  INFO    service/service.go:310  Starting extensions...
1606326171011,"2020-11-25T17:42:51.011Z    INFO    builder/extensions_builder.go:53    Extension is starting...    {""component_kind"": ""extension"", ""component_type"": ""health_check"", ""component_name"": ""health_check""}"
1606326171011,"2020-11-25T17:42:51.011Z    INFO    healthcheckextension/healthcheckextension.go:40 Starting health_check extension {""component_kind"": ""extension"", ""component_type"": ""health_check"", ""component_name"": ""health_check"", ""config"": {""TypeVal"":""health_check"",""NameVal"":""health_check"",""Port"":13133}}"
1606326171011,"2020-11-25T17:42:51.011Z    INFO    builder/extensions_builder.go:59    Extension started.  {""component_kind"": ""extension"", ""component_type"": ""health_check"", ""component_name"": ""health_check""}"
1606326171011,"2020-11-25T17:42:51.011Z    DEBUG   awsxrayexporter@v0.14.1-0.20201111210848-994cabe5d596/conn.go:59    Using proxy address:    {""component_kind"": ""exporter"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""proxyAddr"": """"}"
1606326171011,"2020-11-25T17:42:51.011Z    DEBUG   awsxrayexporter@v0.14.1-0.20201111210848-994cabe5d596/conn.go:125   Fetch region from environment variables {""component_kind"": ""exporter"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""region"": ""us-west-2""}"
1606326171012,"2020-11-25T17:42:51.011Z    DEBUG   awsxrayexporter@v0.14.1-0.20201111210848-994cabe5d596/xray_client.go:56 Using Endpoint: %s  {""component_kind"": ""exporter"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""endpoint"": ""https://xray.us-west-2.amazonaws.com""}"
1606326171012,"2020-11-25T17:42:51.011Z    INFO    builder/exporters_builder.go:306    Exporter is enabled.    {""component_kind"": ""exporter"", ""exporter"": ""awsxray""}"
1606326171012,"2020-11-25T17:42:51.012Z    DEBUG   awsemfexporter@v0.14.1-0.20201117192543-4a81c809e720/conn.go:59 Fetch region from environment variables {""component_kind"": ""exporter"", ""component_type"": ""awsemf"", ""component_name"": ""awsemf"", ""region"": ""us-west-2""}"
1606326171012,"2020-11-25T17:42:51.012Z    INFO    builder/exporters_builder.go:306    Exporter is enabled.    {""component_kind"": ""exporter"", ""exporter"": ""awsemf""}"
1606326171012,2020-11-25T17:42:51.012Z  INFO    service/service.go:325  Starting exporters...
1606326171012,"2020-11-25T17:42:51.012Z    INFO    builder/exporters_builder.go:92 Exporter is starting... {""component_kind"": ""exporter"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray""}"
1606326171012,"2020-11-25T17:42:51.012Z    INFO    builder/exporters_builder.go:97 Exporter started.   {""component_kind"": ""exporter"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray""}"
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/exporters_builder.go:92 Exporter is starting... {""component_kind"": ""exporter"", ""component_type"": ""awsemf"", ""component_name"": ""awsemf""}"
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/exporters_builder.go:97 Exporter started.   {""component_kind"": ""exporter"", ""component_type"": ""awsemf"", ""component_name"": ""awsemf""}"
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/pipelines_builder.go:207    Pipeline is enabled.    {""pipeline_name"": ""traces"", ""pipeline_datatype"": ""traces""}"
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/pipelines_builder.go:207    Pipeline is enabled.    {""pipeline_name"": ""metrics"", ""pipeline_datatype"": ""metrics""}"
1606326171014,2020-11-25T17:42:51.012Z  INFO    service/service.go:338  Starting processors...
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/pipelines_builder.go:51 Pipeline is starting... {""pipeline_name"": ""traces"", ""pipeline_datatype"": ""traces""}"
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/pipelines_builder.go:61 Pipeline is started.    {""pipeline_name"": ""traces"", ""pipeline_datatype"": ""traces""}"
1606326171014,"2020-11-25T17:42:51.012Z    INFO    builder/pipelines_builder.go:51 Pipeline is starting... {""pipeline_name"": ""metrics"", ""pipeline_datatype"": ""metrics""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    builder/pipelines_builder.go:61 Pipeline is started.    {""pipeline_name"": ""metrics"", ""pipeline_datatype"": ""metrics""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    builder/receivers_builder.go:235    Receiver is enabled.    {""component_kind"": ""receiver"", ""component_type"": ""awsecscontainermetrics"", ""component_name"": ""awsecscontainermetrics"", ""datatype"": ""metrics""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    builder/receivers_builder.go:235    Receiver is enabled.    {""component_kind"": ""receiver"", ""component_type"": ""otlp"", ""component_name"": ""otlp"", ""datatype"": ""traces""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    builder/receivers_builder.go:235    Receiver is enabled.    {""component_kind"": ""receiver"", ""component_type"": ""otlp"", ""component_name"": ""otlp"", ""datatype"": ""metrics""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    awsxrayreceiver@v0.14.1-0.20201111210848-994cabe5d596/receiver.go:61    Going to listen on endpoint for X-Ray segments  {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""udp"": ""0.0.0.0:2000""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    udppoller/poller.go:105 Listening on endpoint for X-Ray segments    {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""udp"": ""0.0.0.0:2000""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    awsxrayreceiver@v0.14.1-0.20201111210848-994cabe5d596/receiver.go:73    Listening on endpoint for X-Ray segments    {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""udp"": ""0.0.0.0:2000""}"
1606326171014,"2020-11-25T17:42:51.013Z    DEBUG   proxy/conn.go:98    Fetched region from environment variables   {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""region"": ""us-west-2""}"
1606326171014,"2020-11-25T17:42:51.013Z    INFO    builder/receivers_builder.go:235    Receiver is enabled.    {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray"", ""datatype"": ""traces""}"
1606326171014,2020-11-25T17:42:51.013Z  INFO    service/service.go:350  Starting receivers...
1606326171016,"2020-11-25T17:42:51.014Z    INFO    builder/receivers_builder.go:70 Receiver is starting... {""component_kind"": ""receiver"", ""component_type"": ""awsecscontainermetrics"", ""component_name"": ""awsecscontainermetrics""}"
1606326171016,"2020-11-25T17:42:51.014Z    INFO    builder/receivers_builder.go:75 Receiver started.   {""component_kind"": ""receiver"", ""component_type"": ""awsecscontainermetrics"", ""component_name"": ""awsecscontainermetrics""}"
1606326171016,"2020-11-25T17:42:51.014Z    INFO    builder/receivers_builder.go:70 Receiver is starting... {""component_kind"": ""receiver"", ""component_type"": ""otlp"", ""component_name"": ""otlp""}"
1606326171046,"2020-11-25T17:42:51.045Z    INFO    builder/receivers_builder.go:75 Receiver started.   {""component_kind"": ""receiver"", ""component_type"": ""otlp"", ""component_name"": ""otlp""}"
1606326171046,"2020-11-25T17:42:51.045Z    INFO    builder/receivers_builder.go:70 Receiver is starting... {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray""}"
1606326171046,"2020-11-25T17:42:51.045Z    INFO    awsxrayreceiver@v0.14.1-0.20201111210848-994cabe5d596/receiver.go:98    X-Ray TCP proxy server started  {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray""}"
1606326171046,"2020-11-25T17:42:51.045Z    INFO    builder/receivers_builder.go:75 Receiver started.   {""component_kind"": ""receiver"", ""component_type"": ""awsxray"", ""component_name"": ""awsxray""}"
1606326171046,"2020-11-25T17:42:51.045Z    INFO    healthcheck/handler.go:128  Health Check state change   {""component_kind"": ""extension"", ""component_type"": ""health_check"", ""component_name"": ""health_check"", ""status"": ""ready""}"
1606326171046,2020-11-25T17:42:51.045Z  INFO    service/service.go:253  Everything is ready. Begin running and processing data.
1606326191021,panic: runtime error: invalid memory address or nil pointer dereference
1606326191021,[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1160c3c]
1606326191021,goroutine 98 [running]:
1606326191021,"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/awsecscontainermetrics.getContainerMetrics(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)"
1606326191021,  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.14.1-0.20201118171217-2398a00e4656/awsecscontainermetrics/metrics_helper.go:19 +0x5c
1606326191021,"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/awsecscontainermetrics.(*metricDataAccumulator).getMetricsData(0xc000799d48, 0xc000532630, 0xc00053a380, 0x6a, 0xc0002ea090, 0x88, 0xc00057c360, 0x25, 0xc0001574c0, 0x2, ...)"
1606326191021,  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.14.1-0.20201118171217-2398a00e4656/awsecscontainermetrics/accumulator.go:37 +0x1c5
1606326191021,github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/awsecscontainermetrics.MetricsData(...)
1606326191021,  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.14.1-0.20201118171217-2398a00e4656/awsecscontainermetrics/metrics.go:24
1606326191021,"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver.(*awsEcsContainerMetricsReceiver).collectDataFromEndpoint(0xc0007a8fc0, 0x33012a0, 0xc000382600, 0x2ed133c, 0x16, 0x1, 0x2000100000000)"
1606326191021,  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.14.1-0.20201118171217-2398a00e4656/receiver.go:97 +0x3e5
1606326191021,"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver.(*awsEcsContainerMetricsReceiver).Start.func1(0xc0007a8fc0, 0x33012a0, 0xc000382600)"
1606326191021,  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.14.1-0.20201118171217-2398a00e4656/receiver.go:71 +0xc5
1606326191021,created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver.(*awsEcsContainerMetricsReceiver).Start
1606326191021,  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.14.1-0.20201118171217-2398a00e4656/receiver.go:64 +0xcd
```

Here is the config I'm using for running the container in AWS Fargate:

```
extensions:
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680
      http:
        endpoint: localhost:55681
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp
  awsecscontainermetrics:
processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
exporters:
  awsxray:
  awsemf:
service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp, awsecscontainermetrics]
      processors: [batch/metrics]
      exporters: [awsemf]
  extensions: [health_check]
```

Am I missing something or messing up the config in some way?

**Comment by hossain-rayhan** [comment] 2020-11-25 18:15
Hi @nathanpeck , can you please share the ECS Agent version/ Fargate platform version you are using. Would be easier to reproduce. Thanks.

**Comment by hossain-rayhan** [comment] 2020-11-25 20:40
Had an offline discussion with @nathanpeck . Possibly, we found the root cause. On Fargate, sometimes we don't get a perfect docker stats from ECS Task Metadata Endpoint. Trying to understand if there is a pattern for this case. Will update once I find something meaningful.

**Comment by hossain-rayhan** [comment] 2020-11-30 16:39
Pushed an [image](https://hub.docker.com/repository/docker/rhossai2/aoc) (version: 0.0.16) to my personal dockerHub for testing purpose. @nathanpeck will give a try with this image and share the the update with me.

**Comment by hossain-rayhan** [comment] 2020-12-02 01:19
Pushed an updated image to DockerHub (`rhossai2/aoc:v0.0.19`). @nathanpeck and I tested it. Everything is working fine. Created a PR in the upstream.

**Comment by hossain-rayhan** [comment] 2020-12-04 22:29
PR is merged and tested.

**Closed by hossain-rayhan** 2020-12-04 22:29 UTC
