### ISSUE TITLE
There is a serious issue with the documentation

### ISSUE THREAD

**Issue by navsinha5** [aws-observability/aws-otel-collector#409] opened 2021-03-19 12:19 UTC
Hi,

While referring the documentation both on Github and [here](https://aws-otel.github.io/docs/introduction), found that there is some serious misalignment between the dev team and the documentation.

### Issue 1
At [this ](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/debian-deb-demo.md) page 

```
`sudo echo "loggingLevel=DEBUG >> /opt/aws/aws-otel-collector/etc/extracfg.txt"`
sudo /opt/aws/aws-otel-collector/aws-otel-collector-ctl -a stop
sudo /opt/aws/aws-otel-collector/aws-otel-collector-ctl -a start
```
The last two commands are wrong. It misses `bin` in the path. Also after including `bin` the DEBUG level logging is not enabled.

-------------------------------------------------------------------------------------------------------------------------------------------

### Issue 2
At [this ](https://aws-otel.github.io/docs/setup/build-collector-as-debian) page

```
git clone https://github.com/aws-observability/aws-otel-collector.git
.tools/packaging/debian/create_deb.sh
```

- The above command should be separated in two different lines
- The second command is not correct. It misses a `/` after the `.`
- It throws below error

```
****************************************
Creating deb file for Debian Linux
****************************************
BASE_ROOT: /home/ubuntu/collector/aws-otel-collector/build/linux/debian  agent_version: 0.8.0 AGENT_BIN_DIR_DEB: /home/ubuntu/collector/aws-otel-collector/build/linux/debian
Creating debian folders
Copying application files
cp: cannot stat 'build/linux/aoc_linux_': No such file or directory
```
------------------------------------------------------------------------------------------------------------------------------------
### Issue 3
#403 
---------------------------------------------------------------------------------------------------------------------------
### Issue 4
[This ](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/build-aoc.md) page and [this ](https://aws-otel.github.io/docs/setup/build-collector-as-debian) page mentions two different approaches for Debian and none of them works.
```
 make package-deb
GOBIN=/home/ubuntu/collector/aws-otel-collector/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint
GOBIN=/home/ubuntu/collector/aws-otel-collector/bin go install honnef.co/go/tools/cmd/staticcheck
/home/ubuntu/collector/aws-otel-collector/bin/staticcheck FAILED => static check errors:

-: no export data for "github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network" (compile)

make: *** [Makefile:109: lint-static-check] Error 1
```

--------------------------------------------------------------------------------------------------------------------------
### Issue 5
The setup described in [this ](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/debian-deb-demo.md) page only work when a role is assigned to an EC2 instance and doesn't work with shared credentials file or credentials provided via environment variable.
#407 

-----------------------------------------------------------------------------------------------------------------------------------
### Issue 6
The application is highly unpredictable if used as a standalone application (without containers) and doesn't justify the claim that it is a production ready application.

Suggestion: Please review and test the documentation as it says.

**Comment by vastin** [comment] 2021-03-19 20:11
@navsinha5 Thank you for reporting issues. The document will be updated for Issue 1 and 2. The Issue 3 has been resolved by https://github.com/aws-observability/aws-otel-collector/pull/405.
For Issue 4, would you please provide more information about OS and golang? Just for reference, Github CI workflows build this project on Ubuntu 20.04 with golang 1.6.
For Issue 5, we continue investigation in https://github.com/aws-observability/aws-otel-collector/issues/407.
For Issue 6, please help open ticket to describe the unpredictable issue and we will address it.

**Comment by navsinha5** [comment] 2021-03-22 03:29
Hi @vastin ,

Thanks for addressing these issues.

Issue 4: I am using version 1.16.2 with Ubuntu 20.04. I guess you also meant Golang version 1.16?
Issue 6: This is a general comment about the fact that the setup process hasn't been smooth and doesn't always follow the documentation.

**Comment by vastin** [comment] 2021-03-22 21:03
@navsinha5 Yes, I mean Golang v1.16. Since you used Ubuntu 20.04 and Go 1.16.2 as same as following CI workflow, I don't see any reason why you get build failure. I also verified locally and it passed build.
https://github.com/aws-observability/aws-otel-collector/blob/main/.github/workflows/CI.yml#L41
https://github.com/aws-observability/aws-otel-collector/blob/main/.github/workflows/CI.yml#L48
Please try to clean up and create a fresh setup for build. If it still fails, please open a new ticket including a detail steps to reproduce the build failure.

**Comment by vastin** [comment] 2021-03-22 21:07
All problems have been resolved or will be addressed in separate Github issues and this issue is closed.

**Closed by vastin** 2021-03-22 21:07 UTC
