### ISSUE TITLE
I wanted to filter out namespace related metrics , when I do this node metrics are excluded from the pipeline, I wanted to solve both like i have to filter namespace metric and node related metrics.

### ISSUE THREAD

**Issue by Bharaniev** [aws-observability/aws-otel-collector#2477] opened 2023-11-14 15:05 UTC
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**Environment**
Describe any aspect of your environment relevant to the problem. 
If this is related to a deployment of the ADOT Collector please
provide your Collector config file. 

**Additional context**

**Comment by vsakaram** [comment] 2023-12-04 19:43
Can you please share reproducible example? Or create a ticket through AWS enterprise support in case you have that channel available for you.

**Comment by vsakaram** [comment] 2023-12-04 19:46
Closing this since seems duplicate of https://github.com/aws-observability/aws-otel-collector/issues/2447

**Closed by vsakaram** 2023-12-04 19:46 UTC
